all:
	clear
	g++ -o teste imageloader.cpp Arena.cpp Helicopter.cpp Rect.cpp Circle.cpp Utils.cpp Cube.cpp XMLConfig.cpp File.cpp tinyxml2.cpp main.cpp -lGL -lGLU -lglut -lm
	./teste ../
run:
	./teste
clean:
	rm -rf *o trabalhocg
